import { DEFAULT_WEBCAM_OVERLAY } from "/src/components/video-editor/types.ts";
import { getWebcamFrameSvgPath } from "/src/components/video-editor/webcamFrame.ts";
import { FrameRenderer } from "/src/lib/exporter/frameRenderer.ts";
import { FrameRenderer as ModernFrameRenderer } from "/src/lib/exporter/modernFrameRenderer.ts";
import { ModernVideoExporter } from "/src/lib/exporter/modernVideoExporter.ts";
import { WebcamBackgroundBlurProcessor } from "/src/lib/webcam-effects/WebcamBackgroundBlurProcessor.ts";
history.replaceState(null, "", "/?portrait-smoke");

const assert = (condition, message) => { if (!condition) throw new Error(message); };
const base64 = (bytes) => { let result = ""; for (let i = 0; i < bytes.length; i += 8192) result += String.fromCharCode(...bytes.subarray(i, i + 8192)); return btoa(result); };
const videoReady = (url) => new Promise((resolve, reject) => {
	const v = document.createElement("video"); v.muted = true; v.src = url;
	v.onloadeddata = () => { v.onloadeddata = null; v.onseeked = () => resolve(v); v.currentTime = Math.min(0.25, v.duration / 2); }; v.onerror = () => reject(new Error(`video decode failed: ${v.error?.message}`));
});

window.smokePromise = (async () => {
	const [screen, camera] = await Promise.all(["screen-source.mp4", "camera-source.mp4"].map(async (name) => {
		const url = new URL(`/.tmp/portrait-smoke/${name}`, location.href).href;
		return { url, blob: await (await fetch(url)).blob() };
	}));
	const video = await videoReady(camera.url);
	console.log('SMOKE camera seek completed');
	const webcam = { ...DEFAULT_WEBCAM_OVERLAY, enabled: true, frameStyle: "portrait", mirror: true, reactToZoom: false, shadow: 0, size: 75, margin: 24 };
	const config = { width: 640, height: 480, wallpaper: "#eeeeee", zoomRegions: [], showShadow: false, shadowIntensity: 0, backgroundBlur: 0, zoomMotionBlur: 0, padding: 0, borderRadius: 0, cropRegion: { x: 0, y: 0, width: 1, height: 1 }, webcam, webcamUrl: camera.url, videoWidth: 640, videoHeight: 480, showCursor: false, preferredRenderBackend: "webgl" };
	const files = {};
	const legacy = new FrameRenderer(config);
	legacy.webcamVideoElement = video;
	const legacyCanvas = document.createElement("canvas"); legacyCanvas.width = 640; legacyCanvas.height = 480;
	legacy.drawWebcamOverlay(legacyCanvas.getContext("2d"), 640, 480);
	files["canvas-frame.png"] = legacyCanvas.toDataURL().split(",")[1];
	const mask = legacy.webcamBubbleCanvas;
	assert(mask.width === 216 && mask.height === 360, "Canvas portrait dimensions");
	const pixels = mask.getContext("2d");
	assert(pixels.getImageData(0, 0, 1, 1).data[3] === 0, "transparent paper corner");
	assert(pixels.getImageData(108, 340, 1, 1).data[3] === 255, "upper-body area survives the crop");
	const left = pixels.getImageData(25, 180, 1, 1).data;
	const right = pixels.getImageData(190, 180, 1, 1).data;
	assert(left[1] > left[0] && right[0] > right[1], "mirrored green-left / red-right markers");
	const blur = new WebcamBackgroundBlurProcessor(() => new Worker(window.smokeWorkerUrl, { type: "module" }));
	console.log('SMOKE processing portrait background blur');
	const blurred = await blur.process({ source: video, sourceWidth: 640, sourceHeight: 480, aspectRatio: 0.6, sourceTimeMs: 0, strength: 0.55, targetSize: 360, inferenceFps: 15 });
	assert(blurred.width === 216 && blurred.height === 360, "background blur retains portrait dimensions");
	files["blurred-frame.png"] = blurred.toDataURL().split(",")[1]; blur.dispose();
	const modern = new ModernFrameRenderer(config);
	await modern.initialize();
	console.log('SMOKE GPU initialized');
	const screenCanvas = document.createElement('canvas'); screenCanvas.width=640;screenCanvas.height=480;
	screenCanvas.getContext('2d').fillStyle='#eeeeee';screenCanvas.getContext('2d').fillRect(0,0,640,480);
	const screenFrame = new VideoFrame(screenCanvas, { timestamp: 0 });
	console.log('SMOKE frame created');
	await modern.renderFrame(screenFrame, 0);
	screenFrame.close();
	console.log('SMOKE GPU rendered');
	files["gpu-frame.png"] = modern.getCanvas().toDataURL().split(",")[1];
	assert(modern.webcamLayoutCache.frameStyle === "portrait", "GPU portrait mask");
	assert(modern.webcamLayoutCache.positionX === 400, "GPU right anchoring");
	const comparison = document.createElement("div"); comparison.style.cssText = "display:flex;gap:24px;padding:30px;font:18px sans-serif";
	const preview = document.createElement("div"); preview.innerHTML = "<p>Preview: 3:5 torn-paper frame</p>";
	const frame = document.createElement("div"); frame.style.cssText = `width:216px;height:360px;overflow:hidden;clip-path:path('${getWebcamFrameSvgPath(216,360,90,"portrait")}')`;
	const img = document.createElement("canvas"); img.width=640;img.height=480;img.getContext("2d").drawImage(video,0,0); img.style.cssText="height:360px;width:480px;max-width:none;margin-left:-132px;transform:scaleX(-1)";
	frame.append(img); preview.append(frame); comparison.append(preview);
	const output = document.createElement("div"); output.innerHTML = "<p>Actual GPU render</p>"; const rendered=document.createElement("img");rendered.src=modern.getCanvas().toDataURL();rendered.style.width="640px";output.append(rendered);comparison.append(output);document.body.append(comparison);
	modern.destroy();
	console.log("SMOKE pixel and renderer assertions passed; exporting MP4");
	const exporter = new ModernVideoExporter({ ...config, videoUrl: screen.url, frameRate: 15, bitrate: 2000000, backendPreference: "webcodecs", encodingMode: "quality", onProgress: (p) => { if (p.currentFrame % 15 === 0) console.log(`SMOKE export ${p.percentage}`); } });
	const result = await exporter.export();
	assert(result.success && result.blob, `MP4 export failed: ${result.error}`);
	files["portrait-export.mp4"] = base64(new Uint8Array(await result.blob.arrayBuffer()));
	const exported = await videoReady(URL.createObjectURL(result.blob));
	assert(exported.videoWidth === 640 && exported.videoHeight === 480, "MP4 can be reopened with correct dimensions");
	console.log("SMOKE MP4 successfully exported and reopened");
	return { success: true, duration: exported.duration, width: exported.videoWidth, height: exported.videoHeight, bytes: result.blob.size, checks: ["transparent edges", "3:5 geometry", "upper body preserved", "mirror", "Canvas renderer", "GPU renderer", "production background blur worker", "MP4 export and playback"], files };
})().catch(e => { console.error('SMOKE failure '+String(e)+' '+e?.message+' '+e?.stack+' '+JSON.stringify(e)); throw new Error(String(e?.message || e)); });
